apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-orderly-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps/v1
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - orderly.io
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orderly.io
  resources:
  - queues/finalizers
  verbs:
  - update
- apiGroups:
  - orderly.io
  resources:
  - queues/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - v1
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - v1
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update