apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-queue-viewer-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - orderly.io
  resources:
  - queues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - orderly.io
  resources:
  - queues/status
  verbs:
  - get