---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - orderly.co
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - orderly.co
  resources:
  - queues/finalizers
  verbs:
  - update
- apiGroups:
  - orderly.co
  resources:
  - queues/status
  verbs:
  - get
  - patch
  - update
