apiVersion: v1
kind: Secret
metadata:
  name: queue-sample-secrets
stringData:
  jwtSecret: base64:Hznayfuih4eLnZjtNGiwauq0y999FhJWKA8zGwymaoQ
  encryptionKey: base64:32:eoN9P1NndyYjKoeIyoaKxmaVzYCz32ZEc9V0XmXlFM4=
---
apiVersion: orderly.io/v1beta1
kind: Queue
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: queue-sample
spec:
  encryptionKey:
    secretName: queue-sample-secrets
    secretKey: encryptionKey

  jwtSecret:
    secretName: queue-sample-secrets
    secretKey: jwtSecret

  snapshots:
    enabled: false

  resources:
    limits:
      cpu: 1
      memory: 128Mi
