apiVersion: my.domain/v1beta1
kind: Queue
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: queue-sample
spec:
  # TODO(user): Add fields here
